#!/bin/busybox sh

mount -t devtmpfs none /dev
while [ ! -e "/dev/mmcblk0p1" ]
do
	umount /dev
	sleep 2
	mount -t devtmpfs none /dev
done
mount -t proc none /proc
mount -t sysfs none /sys

DOCACHE="no"
if $(cat /proc/cmdline | tr ' ' '\n' | grep -q docache)
then
	DOCACHE="yes"
fi

mount -t tmpfs tmpfs /mnt
mkdir /mnt/b /mnt/e /mnt/u /mnt/w /mnt/m /mnt/c /mnt/sd

while [ ! -f "/mnt/sd/kernel8.img" ]
do
	mount -o ro -t vfat /dev/mmcblk0p1 /mnt/sd || sleep 1
done

if [ "${DOCACHE}" = "yes" ] || [ -f /base ]
	if [ -f "/mnt/sd/config" ]
	then
		cp /mnt/sd/config /mnt/config
		mount -t squashfs /mnt/config /mnt/c
	fi
	if [ -f /base ]
	then
		mount -t squashfs /base /mnt/b
	else
		cp /mnt/sd/base /mnt/base
		mount -t squashfs /mnt/base /mnt/b
	fi
	if [ -f /extra ]
	then
		mount -t squashfs /extra /mnt/e
	else
		cp /mnt/sd/extra /mnt/base
		mount -t squashfs /mnt/extra /mnt/e
	fi
	umount /mnt/sd
else
	if [ -f "/mnt/sd/config" ]
	then
		mount -t squashfs /mnt/sd/config /mnt/c
	fi
	mount -t squashfs /mnt/sd/base /mnt/b
	mount -t squashfs /mnt/sd/extra /mnt/e
fi

mount -t overlay overlay -olowerdir=/mnt/c:/mnt/e:/mnt/b,upperdir=/mnt/u,workdir=/mnt/w /mnt/m

umount /proc
umount /sys
umount /dev

exec switch_root /mnt/m /sbin/init || exec sh
